### ISSUE TITLE
Question about data split

### ISSUE THREAD

**Issue by unrealMJ** [HeliosZhao/NCDSS#1]
Hi,
thanks for your source code, but I have a question
You use `base_train_fold0.txt` to train a supervised segmentation model f_b in stage1.  Then use f_b to generate predicts for file in `fold0/novel.txt`. However, the part of the filenames are in `base_train_fold0.txt`. I'd like to ask if there has some error.

Hope to get your reply.

**Comment by HeliosZhao** [comment]
Thanks for your interest. 

As mentioned in Sec. 4.1 in our paper, in the base training stage, all images containing base classes are used as training samples, and the novel classes here are viewed as the background class. That is `base_train_fold0.txt`.
While in the clustering pseudo-labeling and novel finetuning stage, the full training set is used, where all images containing novel classes are unlabeled. That is `fold0/novel.txt`. The overlap filename in the two files are images that contain both base and novel classes.

**Comment by unrealMJ** [comment]
Thanks for your reply
Maybe I'm not writing clearly, I mean the `base_train_fold0.txt` can view as the D^l and the `fold0/novel.txt` can view as the D^u. I think they shoule be disjoint. If not, you use the file in `fold0/novel.txt` to train the f_b in base training stage, of course you can get the perfect output in the clustering pseudo-labeling stage.

**Comment by HeliosZhao** [comment]
Hi,

for the base training stage, we use the `base_train_fold0.txt` as the training data, and all the novel classes are viewed as the **background**. We do it as we hope to train the base model with some novel classes not recognized.

In the novel fine-tuning stage, there exist some images containing both novel and base classes in `novel.txt`. Those images are overlapped with `base_train_fold0.txt`. The base classes of those images are used for training in the base training stage, which leads them to be easily recognized. But the novel classes of those images are viewed as the background in the base training stage, so we cannot segment them using the model but use clustering pseudo-labeling to detect them. All the novel classes are unlabeled during the whole training stage.

Anyway, you can also split the data like this: the training data in the base images only contains base classes, and all images containing novel classes are split into novel images. This can avoid the overlapping images but this does not fulfill our assumption that in the base training stages, there are some novel classes unrecognized.

Hope this helps.

**Comment by unrealMJ** [comment]
All right, thanks a lot!
