### ISSUE TITLE
about data_split

### ISSUE THREAD

**Issue by DevinCheung** [HeliosZhao/NCDSS#2]
Hi, thanks for your excellent work!

May I ask how the data/data_split/* are produced? Thanks!

**Comment by HeliosZhao** [comment]
Thanks for your interest in our work!
`data/data_split/base_train_fold*.txt` is the training data that contains **at least one** base class for fold*, which is used in the base training stage. (same with `data/data_split/base_val_fold*.txt`)

`data/data_split/fold*/base.txt` is the base data that **only contains** base classes for fold*, and `data/data_split/fold*/novel.txt` is the other data in the training set, which contains **at least one** novel class. These two data split files are used in the novel fine-tuning stage.
