### ISSUE TITLE
About saliency map

### ISSUE THREAD

**Issue by DevinCheung** [HeliosZhao/NCDSS#5]
hello~

May I ask how you obtain the saliency maps?

I only see the saliency maps of VOC. There are not saliency maps of Cityscapes, nor the saliency model. Could you please provide them, or where can I find them? Thanks!

**Comment by HeliosZhao** [comment]
We use [BASNet](https://github.com/xuebinqin/BASNet) for estimating saliency maps. Specifically, we directly download their pre-trained model and inference on the COCO dataset.

**Comment by HeliosZhao** [comment]
I upload the saliency maps of the COCO dataset to [Google Drive](https://drive.google.com/file/d/1VMH51A4OVGXg-0mQsE60dsKZ4sxy66bX/view?usp=sharing) for your reference.

**Comment by DevinCheung** [comment]
Thanks for your reply!
